In [ ]:
import numpy as np
import time

# Python list
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [x + y for x, y in zip(list1, list2)]
end = time.time()
print(result[0:20])
print("Python list addition time:", end - start)

# NumPy array
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
result = arr1 + arr2  # Vectorized operation
end = time.time()
print(result[0:20])
print("NumPy array addition time:", end - start)












[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]
Python list addition time: 0.37123608589172363
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
NumPy array addition time: 0.18418526649475098


In [ ]:
import numpy as np
arr=np.array([[1,2,3],
         [3,5,6]])
print(type(arr))
arr.shape

<class 'numpy.ndarray'>


(2, 3)

In [ ]:
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 8000 bytes


In [ ]:
import numpy as np
import time
list=[1,2,3,4,5,6,7,8,9,10]
start=time.time()
list_squares=[x**2 for x in list]
end=time.time()
print(list_squares)
print(end-start)
start=time.time()

numpy_squares=np.array(list)**2
end=time.time()
print(numpy_squares)
print(end-start)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
0.0005092620849609375
[  1   4   9  16  25  36  49  64  81 100]
0.0001723766326904297


# New Section

In [ ]:
import numpy as np
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
arr=np.eye((4),dtype='int')
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
a=1
np.arange(a,100,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr = np.array([10, 20, 30, 40])
print(arr[0])  # 10
print(arr[-1]) # 40

10
40


In [ ]:
arr[1:3]

array([20, 30])

In [ ]:
arr1=np.array([[1,3,5],[2,4,6],[5,8,9]])
print(type(arr1))
arr1.shape

<class 'numpy.ndarray'>


(3, 3)

In [ ]:
arr2=np.array([[1.1,2.2,3.3]],'int')
arr2.dtype
print(arr2)

[[1 2 3]]


In [ ]:
arr3=np.array([1,2,3,4,5,6])
for x in arr3:
  if arr3[x]%2==0:
    print(arr3[x])


2
4
6


IndexError: index 6 is out of bounds for axis 0 with size 6

In [ ]:
arr3 = np.array([1, 2, 3, 4, 5, 6])
even_mask = arr3 % 2 == 0 # Create a boolean mask
print(arr3[even_mask]) # Use the mask to select even numbers

[2 4 6]


In [ ]:
arr3 = np.array([1, 2, 3, 4, 5, 6])
for i in range(len(arr3)): # Iterate through indices
  if arr3[i] % 2 == 0:
    print(arr3[i])

2
4
6


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(np.sum(arr, axis=0))  # Sum along rows (down each column)
print(np.sum(arr, axis=1))  # Sum along columns (across each row)

[12 15 18]
[ 6 15 24]


In [ ]:
# Accessing an element
print(arr[1, 2])  # Row index 1, Column index 2 → Output: 6

6


In [ ]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3)
# First sheet, second row, third column
print(arr3D[0, 1, 2])  # Output: 6

print(arr3D[:, 0, :])   # Get the first row from both sheets
# Get all rows of the first column
first_col = arr[:, 0]
print(first_col)  # Output: [1 4 7]
# Get the first row from each "sheet" in a 3D array
first_rows = arr3D[:, 0, :]
print(first_rows)

(2, 2, 3)
6
[[1 2 3]
 [7 8 9]]
[1 4 7]
[[1 2 3]
 [7 8 9]]


In [ ]:
arr = np.array([1.5, 2.7, 3.9])
print(arr.dtype)  # Output: float64

arr_int = arr.astype(np.int32)  # Converting float to int
print(arr_int)    # Output: [1 2 3]
print(arr_int.dtype)  # Output: int32

float64
[1 2 3]
int32


In [ ]:
arr_large = np.array([1000000, 2000000, 3000000], dtype=np.int64)
arr_small = arr_large.astype(np.int32)  # Downcasting to a smaller dtype
print(arr_small)  # Output: [1000000 2000000 3000000]
print(arr_small.dtype)  # Output: int32

[1000000 2000000 3000000]
int32


In [ ]:
arr_int64 = np.array([1, 2, 3], dtype=np.int64)
arr_int32 = np.array([1, 2, 3], dtype=np.int32)

print(arr_int64.nbytes)  # Output: 24 bytes (3 elements * 8 bytes each)
print(arr_int32.nbytes)  # Output: 12 bytes (3 elements * 4 bytes each)
arr = np.array(['apple', 'banana', 'cherry'], dtype='U10')  # Unicode string array
print(arr)
arr = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype='complex128')
print(arr)
arr = np.array([{'a': 1}, [1, 2, 3], 'hello'], dtype=object)
print(arr)

24
12
['apple' 'banana' 'cherry']
[1.+2.j 3.+4.j 5.+6.j]
[{'a': 1} list([1, 2, 3]) 'hello']
